[package]
name = "populate"
version = "0.1.0"
authors = ["Josh Matthews <josh@joshmatthews.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ureq = "1"
kuchiki = "0.8"
random-number = "0.1"
serde_json = "1"
